### ISSUE TITLE
Publish Bionic packages

### ISSUE THREAD

**Issue by strk** [linz/linz_utils_perl#21]
Once tested (#20)

**Comment by strk** [comment]
Pushing build-area/liblinz-utils-perl_1.1.0-1linz~bionic1_all.deb... success!

Keeping open until promoted to production

**Comment by imincik** [comment]
@strk , we are promoting packages from `test` repo branch to `prod` after BDE Processor UAT is done (https://github.com/linz/bde-processor-deployment/wiki/Production-Deployment#production-deployment). I think we don't need this ticket. Will close it.
