### ISSUE TITLE
Time based tests are unpredictable

### ISSUE THREAD

**Issue by strk** [linz/linz_utils_perl#27]
The `t/Config.t` files compares time variables (_runtime, _year, _second, ...) to an expected value. But the value to expect is not easy to predict as it depends on how much time instanciating the LINZ::Config class takes. We should make the tests more tolerant (like checking time _before_ and after instanciation and allow for the time to be in that range?)

**Comment by imincik** [comment]
I agree @strk , would you please do it ? Thanks
