### ISSUE TITLE
Document how to install from packages, if any

### ISSUE THREAD

**Issue by strk** [linz/linz_utils_perl#6]
I have the impression there are binary packages available somewhere (looking at the `debian/`) subdir, so this ticket is to document how to find those packages (if anywhere publicly) for easy install.

If there are other ways (CPAN?) that's also useful to document.

**Comment by palmerj** [comment]
The binaries are currently in LINZ PPA. Please talk to @imincik for more details on how to access.

**Comment by strk** [comment]
This ticket is to have access method documented in the README.
@imincik please report here the coordinates to the LINZ PPA if you want me to take care of the documentation for this aspect.

**Comment by imincik** [comment]
URL to private LINZ PPA is following: https://{{ linz_repository_username }}:{{ linz_repository_password }}@private-ppa.launchpad.net/linz/prod/ubuntu

But I don't think we need to document it here

**Comment by strk** [comment]
Maybe though we can at least document how to *build* the package, as it is [done](https://github.com/linz/postgresql-tableversion/blob/master/README.md#building-debian-packaging) for postgresql-tableversion

**Comment by imincik** [comment]
I agree, how to build package should be documented. @strk , would you please take a care of it ?

**Comment by strk** [comment]
I've documented how to build a binary package. Source package I still dunno how to create it (same issue than with https://github.com/linz/postgresql-tableversion/issues/29 - maybe you can look at it @imincik ?)

**Comment by imincik** [comment]
I fine tuned your README patch and I think it is enough. How to build Debian source packages and other packaging docs is out of scope here.
